### ISSUE TITLE
Chaos Islands not spawning; Unable to get Chaos Shards

### ISSUE THREAD

**Issue by Testybeds** [FTBTeam/FTB-Sky-Adventures#196]
* **Modpack Version**:  1.2.1 

* **Issue**: Flying to the 10k, 10k coordinates didn't have the expected Chaos Island.  How else am I supposed to get the chaos shards? 
* **Link to Log or Crash File Paste**: n/a
* **Is it Repeatable?**: yes

* **Mod/s Affected**:  Draconic Evolution 

* **Known Fix**: Add an alternative method to acquire them?

**Comment by twsx** [comment]
Seems to work fine for me. Just tested 10'000,0 and 10'000,10'000 – Islands spawned properly in both cases.
Also no indication in configs that they aren't supposed to spawn.

That being said, if the problem persists for you, you CAN get the small shards from the quest reward store, although that will be a pain, because you'd need to turn it in 729 times per shard...
Small workaround (for the quest turn in); Put this in a new .zs file in your /scripts/ folder:

    recipes.addShapeless(<draconicevolution:chaos_shard:3>, [<modcurrency:banknote:5>]);

That will allow you to "craft" the fragments with 100$ bills, instead of having to do the clicking game 700+ times.

**Comment by tfox83** [comment]
Try a fresh world, I get the islands everytime with a new world in testing.
