### ISSUE TITLE
Wireless crafting terminal

### ISSUE THREAD

**Issue by dj-holy** [FTBTeam/FTB-Sky-Adventures#213]
Modpack Version 1.3.0

Wireless crafting terminal from Wireless crafting Terminal mod cant Extract/Insert Items anymore

Tried with crafting new Terminals. Normal Wireless terminal from AE2 works.

**Comment by Caraxi** [comment]
I'm also experiencing issues with the Wireless Crafting Terminal.

I've found that I can extract items by right clicking them, but there is no working way to take full stacks or put items in.

**Comment by shortybsd** [comment]
Modpack author should update Wireless Crafting Terminal to 1.12.2-3.10.80. As this was fixed - https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2612298
Changelog "Updated to reflect AE2's Platform IAEStack insertion/extraction changes"

**Comment by shortybsd** [comment]
> 
> 
> I'm also experiencing issues with the Wireless Crafting Terminal.
> 
> I've found that I can extract items by right clicking them, but there is no working way to take full stacks or put items in.

You can put items back in by right clicking, only one at a time though.

**Comment by dm8mydog** [comment]
can be fixed by upgrading the version of the wireless crafting terminal mod and it's dependencies.

### Wireless Crafting Terminal
https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files

### AE2 Wireless Terminal Library (new dep for this modpack)
https://minecraft.curseforge.com/projects/ae2-wireless-terminal-library/files

### p455w0rd's Library
https://minecraft.curseforge.com/projects/p455w0rds-library/files

**Comment by tfox83** [comment]
This has been fixed in 1.4.0
