### ISSUE TITLE
Crash loading the mod pack (Just enough items)

### ISSUE THREAD

**Issue by BTCCBaker** [FTBTeam/FTB-Sky-Adventures#245]
* **Modpack Version**: FTB Sky Adventures 1.3.0 - 1.12.2

* **Issue**: Trying to load the mod pack for the first time, loading goes super quick until it starts loading Just Enough Items. The following error message occurs after the crash: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
The loading screen gets to stage 6/7 on the top bar. 
The middle bar shows 'Load complete- Just Enough Items 17/195
The bottom bar gets to 'Loading Recipes 131863/216948' then it crashes. 

* **Link to Log or Crash File Paste**: <!--connection keeps timing out while loading the website for this.

* **Is it Repeatable?**: yes, also tried uninstalling and re-installing. same issue repeats.

* **Mod/s Affected**: Just Enough Items. Believe the version to be 4.13.0 (Taken from file name in crash log)

* **Known Fix**: Was hoping you would know ;)

**Comment by Jacykow** [comment]
I have exactly the same problem

**Comment by Amryu** [comment]
Yes this problem is due to the JRE not having enough RAM.

If you look closer it shows you an OutOfMemoryException. To fix this (temporarily) open the Minecraft launcher and not click start yet. Click "Profiles" then select "FTB SKY ADVENTURES". You should find the following text for "JVM Arguments: 

`-Xmx3072m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="E:\Curse\Minecraft\Instances\FTB Sky Adventures" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US`

We care about the first argument "-Xmx3072m" which specifies the maximum amount of RAM being used. I change that to "-Xmx6G" so it gets up to 6GB RAM. This is the maximum amount of RAM Java will use, not the amount that it is using.

Keep in mind that the Twitch launcher (which I am using) resets that profile every time you start the game so you have to do this every time. Hope this helps :)

P.S. More RAM will also make the loading faster and gameplay smoother.

**Comment by BTCCBaker** [comment]
I had been doing that for continuum and sky factory! I thought I had done that when trying to load Sky adventures... I guess I wasn't haha. All sorted! thank you! :D
