### ISSUE TITLE
EMC Loop

### ISSUE THREAD

**Issue by PiggyWhiskey** [FTBTeam/FTB-Sky-Adventures#33]
Iron Nuggets x9 = 72 EMC
Iron Ingots = 256 EMC
Profit: 184 EMC per craft.

With compacting drawers, this is very easily breakable and very very early game

**Comment by tfox83** [comment]
removed all EMC from nuggets in dev

**Comment by Scarsz** [comment]
That seems like a horrible solution to this issue. Nuggets should still have EMC because otherwise they’re yet another thing taking up storage space to a newer player. If the metal has EMC, bits of it should have EMC as well.

The correct solution to this problem would be setting the EMC for nuggets to 28.
